/**
 * 示范 seeds for H2/H3 (spec §5.1, §8.10): for every level, the 领航员 (EXPERT model + the level's hook) is
 * run on seeds 9001… until a few successes; the fastest success is kept with its key moment (§5.1 table) and
 * the level's content hash. The page replays a demo live from that seed (the sim is deterministic, V1b/V15)
 * and slows down 0.5× at the key moment as it happens. Run: SB_DEMOS=1 npx vitest run …/record-demos.test.ts
 * → writes content/snake-battle/demos.json.
 */
import fs from 'node:fs';
import { describe, expect, it } from 'vitest';
import { MISSIONS, MissionRun, type Mission } from '../src/sim/mission';
import { hashString } from '../src/sim/core';
import type { SimEvent } from '../src/sim/world';

export const contentHash = (m: Mission) => (hashString(JSON.stringify(m)) >>> 0).toString(16).padStart(8, '0');

function keyMoment(m: Mission, run: MissionRun, notes: { kind: string; t: number; n?: number }[], evs: SimEvent[]) {
  const me = run.me.id, o = m.objective;
  const first = (f: (e: SimEvent) => boolean) => evs.find(f)?.t;
  if (m.ai.some((a) => a.crown)) return first((e) => e.type === 'gem' && e.by === me);
  switch (o.type) {
    case 'rings': {
      // the hardest ring = the one closest to a rock or a sleeping body
      const obs = m.arena.obstacles ?? []; const sl = m.ai.filter((a) => a.path).flatMap((a) => a.path!);
      let best = Math.floor(o.points!.length / 2), bd = 1e9;
      o.points!.forEach((p, i) => { for (const ob of obs) { const d = Math.hypot(p[0] - ob.x, p[1] - ob.y) - ob.r; if (d < bd) { bd = d; best = i; } } for (const q of sl) { const d = Math.hypot(p[0] - q[0], p[1] - q[1]); if (d < bd) { bd = d; best = i; } } });
      return notes.find((n) => n.kind === 'ring' && n.n === best + 1)?.t;
    }
    case 'eat':
      if (o.kind === 'meteor') return first((e) => e.type === 'meteor' && e.id === me);
      if (o.kind === 'drop') return first((e) => e.type === 'eat' && e.id === me && e.kind === 'drop');
      return first((e) => e.type === 'pu' && e.id === me && e.kind === 'magnet') ?? first((e) => e.type === 'eat' && e.id === me && e.kind === 'big');
    case 'length': return first((e) => e.type === 'pu' && e.id === me && e.kind === 'magnet') ?? first((e) => e.type === 'eat' && e.id === me && e.kind === 'big');
    case 'pu': return first((e) => e.type === 'pu' && e.id === me && e.kind === o.kind);
    case 'survive': return first((e) => e.type === 'nearmiss' && e.id === me);
    case 'loop': return notes.find((n) => n.kind === 'marker')?.t;
    default: return first((e) => e.type === 'kill' && e.killer === me && e.tag !== 'headon' && (!o.tags || o.tags.includes(e.tag)));
  }
}

describe.skipIf(!process.env.SB_DEMOS)('record 示范 seeds', () => {
  it('one demo per level', () => {
    const out: Record<string, { seed: number; model: string; t: number; keyT: number | null; contentHash: string }> = {};
    const misses: string[] = [];
    for (const m of MISSIONS) {
      let best: (typeof out)[string] | null = null; let wins = 0;
      for (let k = 1; k <= 40 && wins < 4; k++) {
        const run = new MissionRun(m, 9000 + k, { bot: { tier: 'EXPERT', persona: 'expert' } });
        run.w.keepEvents = true;
        const notes: { kind: string; t: number; n?: number }[] = [];
        run.onNote = (n) => notes.push({ kind: n.kind, t: run.w.t, n: n.n });
        while (!run.step());
        const r = run.result();
        if (!r.ok) continue;
        wins++;
        const keyT = keyMoment(m, run, notes, run.w.events) ?? null;
        if (!best || r.t < best.t) best = { seed: 9000 + k, model: 'EXPERT', t: Math.round(r.t * 10) / 10, keyT: keyT === null ? null : Math.round(keyT * 10) / 10, contentHash: contentHash(m) };
      }
      if (best) out[m.id] = best; else misses.push(m.id);
    }
    fs.writeFileSync(new URL('../../../content/snake-battle/demos.json', import.meta.url), JSON.stringify({ version: 1, note: 'generated by site/snake-battle/validate/record-demos.test.ts (SB_DEMOS=1)', demos: out }, null, 1) + '\n');
    expect(misses, `no EXPERT success in 40 seeds: ${misses.join(', ')}`).toEqual([]);
  }, 3600_000);
});
