/**
 * V15 in WebKit (spec §8.10/§9.2): every 示范 in content/snake-battle/demos.json replays in the Safari engine with
 * ok = true and the finish time and key moment within ±0.2 s of the recorded (Node) values — the page re-simulates
 * demos live, and V8/JSC differ on transcendental Math, so a seed is only kept if both engines agree.
 *
 * SB_DEMOS_PICK=1 → picking pass: reads ~/kid-games-work/snake-battle/demo-candidates.json (record-demos.test.ts)
 * and writes demos.json with the first candidate per level that agrees in WebKit.
 * Needs the dev server (imports the sim sources); skipped against a built preview.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { test, expect, type Page } from '@playwright/test';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const DEMOS = path.join(ROOT, 'content/snake-battle/demos.json');
const CANDIDATES = path.join(os.homedir(), 'kid-games-work/snake-battle/demo-candidates.json');
type Rec = { seed: number; model: string; t: number; keyT: number | null; contentHash: string };
type Res = { ok: boolean; t: number; keyT: number | null };

async function webkitRuns(page: Page, jobs: { id: string; seed: number }[]): Promise<Res[]> {
  return page.evaluate(async (jobs) => {
    const load = (u: string) => import(/* @vite-ignore */ u);   // served by the dev server (vite root = site/)
    const mission = await load('/snake-battle/src/sim/mission.ts');
    const dk = await load('/snake-battle/src/demo-key.ts');
    return jobs.map((j: { id: string; seed: number }) => dk.runDemo(mission.MISSION_BY_ID[j.id], j.seed, mission.MissionRun));
  }, jobs);
}
const agree = (a: Res, r: { t: number; keyT: number | null }) => a.ok && Math.abs(a.t - r.t) <= 0.2 && a.keyT !== null && r.keyT !== null && Math.abs(a.keyT - r.keyT) <= 0.2;

test.describe('V15 demos replay in WebKit', () => {
  test.skip(({ browserName }) => browserName !== 'webkit');
  test.beforeEach(async ({ page }, info) => {
    test.skip(info.project.name.startsWith('landscape'), 'engine check, one orientation is enough');
    const r = await page.request.get('/snake-battle/src/demo-key.ts').catch(() => null);
    test.skip(!r || !r.ok(), 'needs the dev server (sim sources)');
    await page.goto('/snake-battle/?test=1&nogate'); await page.waitForSelector('#app[data-ready]');
  });

  test('all 40 demos: ok, t and key moment within ±0.2 s', async ({ page }) => {
    test.skip(!!process.env.SB_DEMOS_PICK);
    test.setTimeout(600_000);
    const demos = JSON.parse(fs.readFileSync(DEMOS, 'utf8')).demos as Record<string, Rec>;
    const ids = Object.keys(demos);
    expect(ids.length).toBe(40);
    const bad: string[] = [];
    for (let i = 0; i < ids.length; i += 5) {
      const chunk = ids.slice(i, i + 5);
      const res = await webkitRuns(page, chunk.map((id) => ({ id, seed: demos[id].seed })));
      chunk.forEach((id, k) => { if (!agree(res[k], demos[id])) bad.push(`${id} webkit ${JSON.stringify(res[k])} vs ${demos[id].t}/${demos[id].keyT}`); });
    }
    expect(bad).toEqual([]);
  });

  test('pick demo seeds that agree in Node and WebKit', async ({ page }) => {
    test.skip(!process.env.SB_DEMOS_PICK);
    test.setTimeout(3_000_000);
    const cand = JSON.parse(fs.readFileSync(CANDIDATES, 'utf8')) as Record<string, Rec[]>;
    const prev = JSON.parse(fs.readFileSync(DEMOS, 'utf8'));
    const out: Record<string, Rec> = {}; const miss: string[] = [];
    for (const id of Object.keys(prev.demos)) {
      const list = cand[id] ?? [];
      let picked: Rec | null = null;
      for (const c of list) {
        const [r] = await webkitRuns(page, [{ id, seed: c.seed }]);
        if (agree(r, c)) { picked = c; break; }
        console.log(`${id} seed ${c.seed}: webkit ${JSON.stringify(r)} vs node ${c.t}/${c.keyT} — next`);
      }
      if (picked) out[id] = picked; else miss.push(id);
    }
    expect(miss, `no candidate agrees in WebKit: ${miss.join(', ')}`).toEqual([]);
    fs.writeFileSync(DEMOS, JSON.stringify({ version: 2, note: 'generated by site/snake-battle/validate/record-demos.test.ts (SB_DEMOS=1) + tests/demos.spec.ts (SB_DEMOS_PICK=1): EXPERT successes with a key moment, median-nearest, agreeing in Node and WebKit', demos: out }, null, 1) + '\n');
  });
});
