"""Number clips 0..1000 (+ 两 variants) for counting / reading numbers aloud.

ids: num.<n>            standard reading       205 -> 二百零五, 2 -> 二, 1000 -> 一千
     num.<n>.liang      colloquial 两 reading  2 -> 两, 200..299 -> 两百…  (两个 / 两百块)
`text` is the digits (what a subtitle shows), `norm` the reading (what the engine says).
"""
from __future__ import annotations
from pathlib import Path

import yaml

from .textnorm import int2cn


def readings(max_n: int = 1000):
    for n in range(0, max_n + 1):
        cn = int2cn(n)
        yield f"num.{n}", n, cn
        if n == 2 or (200 <= n <= 299):
            yield f"num.{n}.liang", n, "两" + cn[1:]


def to_yaml(game: str = "numbers", role: str = "companion", max_n: int = 1000, sample: list[str] | None = None) -> str:
    lines = []
    for lid, n, cn in readings(max_n):
        if sample and lid not in sample:
            continue
        lines.append({"id": lid, "role": role, "text": str(n), "norm": cn})
    doc = {"game": game, "seed": 1234, "lines": lines}
    head = (f"# generated by `python -m voice numbers` — {len(lines)} clips "
            f"(0..{max_n}{', sample' if sample else ''}; .liang = 两 variant)\n")
    return head + yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=200)


def write(path: Path, **kw) -> int:
    text = to_yaml(**kw)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, "utf-8")
    return text.count("\n- id:") + text.count("\n  - id:")
