#!/usr/bin/env node
// Every CJK character the 陆战棋 page can display (spec §6.9, §8.12 platform request 3): narration
// lines, lessons, endgames, cards, templates and the literals in the page code. Written to
// content/military-chess/display-text.txt for the design system's font subsetter.
//   node tools/military-chess/dump-text.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const CJK = /[　-〿㐀-鿿＀-￯]/gu;
const chars = new Set();
const take = (s) => {
  for (const c of s.match(CJK) ?? []) chars.add(c);
};
for (const f of ['lines.json', 'lessons.json', 'endgames.json', 'cards.json', 'templates.json']) take(fs.readFileSync(path.join(ROOT, 'content/military-chess', f), 'utf8'));
const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(dir, e.name)) : e.name.endsWith('.ts') ? [path.join(dir, e.name)] : []));
for (const f of walk(path.join(ROOT, 'site/military-chess/src'))) {
  // string and template literals only (comments are not displayed)
  const src = fs.readFileSync(f, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '').replace(/([^:])\/\/ .*$/gm, '$1');
  for (const m of src.matchAll(/'([^'\n]*)'|"([^"\n]*)"|`([^`]*)`/g)) take(m[1] ?? m[2] ?? m[3] ?? '');
}
const list = [...chars].sort();
const out = path.join(ROOT, 'content/military-chess/display-text.txt');
fs.writeFileSync(out, `# 陆战棋 display characters (${list.length}), generated by tools/military-chess/dump-text.mjs\n${list.join('')}\n`);
console.log(`dump-text: ${list.length} characters → ${path.relative(ROOT, out)}`);
